# Generated by Django 3.2.5 on 2021-07-07 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(default='', max_length=200)),
                ('lang', models.CharField(choices=[('python', 'Python'), ('c#', 'C#'), ('c++', 'C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift')], default='python', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('tags', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
            ],
        ),
    ]
