# Generated by Django 3.2.4 on 2021-06-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True)),
                ('tags', models.CharField(max_length=200)),
                ('difficulty', models.CharField(max_length=200)),
            ],
        ),
    ]
