# Generated by Django 3.2.4 on 2021-06-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='c_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='challenge',
            name='lang',
            field=models.CharField(choices=[('python', 'Python'), ('c#', 'C#'), ('c++', 'C++'), ('java', 'Java'), ('javascript', 'Javascript'), ('php', 'PHP'), ('ruby', 'Ruby'), ('swift', 'Swift')], default='python', max_length=40),
        ),
    ]
